### ISSUE TITLE
SharePoint related functions

### ISSUE THREAD

**Issue by mkacwork** [Auckland-Council-CC-Insights-Team/tere#14]
Suggestion: 
Consider updating variable names for SharePoint related functions (currently MY_SHAREPOINT_FILES)

Rationale:
I&A now has different sources for data, some of it is in CC Insights & Analysis Team - File Storage and others in CC Insights & Analysis Team - Data Storage. There is a need to differentiate between these sources and any other future sources. 

Possible solution:
When create_environment_variable is called, give the user an option to use their own variable name (e.g. "I_AND_A_DATA_Storage", "FILE_STORAGE") as well as their locally-synchronised SharePoint directory

**Comment by lddurbinAC** [comment]
If I understand what you're saying correctly, this is already possible when calling create_environment_variable. See: https://github.com/Auckland-Council-CC-Insights-Team/tere/blob/5540aef3dd9e1e0511ba99a69dbff86a0700d97c/R/get_started.R#L102

**Comment by mkacwork** [comment]
You saw the future! I'll close this issue

**Comment by mkacwork** [comment]
Is it possible for other functions to point to a different variable? Will they need to be explicitly specified whenever it's different to MY_SHAREPOINT_FILES (since this is the default)

e.g.
https://github.com/Auckland-Council-CC-Insights-Team/tere/blob/5540aef3dd9e1e0511ba99a69dbff86a0700d97c/R/get_started.R#L15

https://github.com/Auckland-Council-CC-Insights-Team/tere/blob/5540aef3dd9e1e0511ba99a69dbff86a0700d97c/R/get_started.R#L35C46-L35C65

https://github.com/Auckland-Council-CC-Insights-Team/tere/blob/5540aef3dd9e1e0511ba99a69dbff86a0700d97c/R/get_started.R#L73
